; -----------------------------------------------------------------------
; Template source file generated by piklab
    #include <p16f688.inc>

; -----------------------------------------------------------------------
; Configuration bits: adapt to your setup and needs
    __config (_FCMEN_OFF & _IESO_OFF & _BOD_NSLEEP & _CPD_OFF & _CP_OFF & _MCLRE_OFF & _PWRTE_OFF & _WDT_OFF & _INTOSCIO)


; -----------------------------------------------------------------------
; Változó értékadás
INT_VAR UDATA_SHR
randomlo	RES 1
randomhi RES 1
w1	RES 1
w2	RES 1
w3	RES 1
tmp1	RES 1
tmp2	RES 1
sor	RES 1
oszlop	RES 1
trisor	RES 1
trioszlop	RES 1

; -----------------------------------------------------------------------
; reset vector
STARTUP CODE 0x000

;RA0 sor1
;RA1 sor2
;RA2 sor3
;RA3 
;RA4 sor4
;RA5 sor5
;RC0 sor1
;RC1 sor2
;RC2 sor3
;RC3 poti
;RC4 sor4
;RC5


start
    movlw	0x5A
    movwf	randomlo
    movwf	randomhi
    clrf	PORTC
    clrf	PORTA
    bsf		STATUS,RP0
    movlw	0x80
    movwf	ANSEL		; AN7 (RC3) analog
    bsf		ADCON1,6	; internal ADC timing
    bcf		STATUS,RP0
    movlw	b'00000111'
    movwf	CMCON0		; RA2 i/o mode
    movlw	b'00011101'	; AN7, left justified
    movwf	ADCON0
    movlw	0x01
    movwf	w3
    movwf	w1
    
    

cikl
    decfsz	w1
    goto	cikl
    movlw	0x80
    movwf	w1

;    decfsz	w2
;    goto	cikl
    
    decfsz	w3
    goto	cikl
    
sample    			; ADC sampling
    bsf		ADCON0,GO
    btfsc	ADCON0,GO
    goto	sample
    movf	ADRESH,w
    movwf	w3

sorujra
    call	rand
    movlw	b'00110111'	; RA 0 1 2  4 5
    andwf	tmp2,w
    btfsc	STATUS,Z
    goto	sorujra
    movwf	sor
    xorlw	0xff
    movwf	trisor
oszlopujra    
    call	rand
    movlw	b'00010111'	; RC 0 1 2  4
    andwf	tmp2,w
    btfsc	STATUS,Z
    goto	oszlopujra
    movwf	oszlop
    xorlw	0xff
    movwf	trioszlop

;   ez a resz talalja ki a polaritast

    call	rand
    btfsc	randomlo,0
    clrf	sor
    btfss	randomlo,0
    clrf	oszlop

; ez a rész rakja ki

    movf	oszlop,w
    movwf	PORTC
    movf	sor,w
    movwf	PORTA
    movf	trioszlop,w
    bsf		STATUS,RP0
    movwf	TRISC
    movf	trisor,w
    movwf	TRISA
    bcf		STATUS,RP0
    goto	cikl

    
rand
    rlf     randomhi,w
    RLF     randomlo,f
    rlf     randomhi,f
    movf    randomlo,w
    BTFSC   randomhi,4
    XORLW   1
    BTFSC   randomhi,5
    XORLW   1
    BTFSC   randomhi,1
    XORLW   1
    addwf   randomhi,w
    MOVWF   randomlo
    andlw	0x07
    btfsc	STATUS,Z
    goto	rand
    movwf	tmp1
    clrf	tmp2
    bsf		STATUS,C
cirik
    rlf		tmp2,f
    bcf		STATUS,C
    decfsz	tmp1,f
    goto	cirik
    return

END
